version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  fastapi:
    container_name: fastapi
    build:
      context: ./servers/fastapi
    ports:
      - '${FASTAPI_PORT}:${FASTAPI_PORT}'
    environment:
      - FASTAPI_PORT=${FASTAPI_PORT}
    depends_on:
      - mongodb

  fastify:
    container_name: fastify
    build:
      context: ./servers/fastify
    ports:
      - '${FASTIFY_PORT}:${FASTIFY_PORT}'
    environment:
      - FASTIFY_PORT=${FASTIFY_PORT}
    depends_on:
      - mongodb

  hono:
    container_name: hono
    build:
      context: ./servers/hono
    ports:
      - '${HONO_PORT}:${HONO_PORT}'
    environment:
      - HONO_PORT=${HONO_PORT}
    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local

networks:
  default:
    name: benchmark
